# Generated by Django 5.1.1 on 2024-10-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_event_registered_users_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
